{% set name = "aws-crt-cpp" %}
{% set version = "0.37.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2bada1b314dcf6f4acbc1db648088bd4933445b02c13d8580ae1ed4f85d6ab84
  patches:
    - patches/0001-use-C-style-for-including-inttypes-in-bin-mqtt5_cana.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-crt-cpp", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
  host:
    - aws-c-auth 0.9.4
    - aws-c-cal 0.9.13
    - aws-checksums 0.2.10
    - aws-c-common 0.12.6
    - aws-c-event-stream 0.6.0
    - aws-c-http 0.10.7
    - aws-c-io 0.23.3
    - aws-c-mqtt 0.13.3
    - aws-c-s3 0.12.0
    - aws-c-sdkutils 0.2.4
test:
  commands:
    - test -f $PREFIX/lib/libaws-c-io${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/io/io.h  # [unix]
    - if not exist %LIBRARY_INC%\aws\io\io.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\aws-c-io.dll exit 1  # [win]
about:
  home: https://github.com/awslabs/aws-crt-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ wrapper around the aws-c-* libraries.
  description: |
    C++ wrapper around the aws-c-* libraries. Provides Cross-Platform Transport Protocols and SSL/TLS implementations for C++.
  doc_url: https://awslabs.github.io/aws-crt-cpp
  dev_url: https://github.com/awslabs/aws-crt-cpp
extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp